#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <iomanip>
#include <algorithm>

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cout << "Usage: st-bin2rsx <input_file> <array_name> [output_header.h]\n";
        return 1;
    }

    std::string input_path = argv[1];
    std::string array_name = argv[2];
    std::string output_path = (argc > 3) ? argv[3] : (array_name + ".h");

    std::ifstream ifs(input_path, std::ios::binary);
    if (!ifs) {
        std::cerr << "Error: Could not open " << input_path << "\n";
        return 1;
    }

    std::vector<uint8_t> data((std::istreambuf_iterator<char>(ifs)), 
                               std::istreambuf_iterator<char>());

    std::ofstream ofs(output_path);
    if (!ofs) {
        std::cerr << "Error: Could not create " << output_path << "\n";
        return 1;
    }

    // Header guard
    std::string guard = array_name;
    std::transform(guard.begin(), guard.end(), guard.begin(), ::toupper);
    
    ofs << "#ifndef " << guard << "_H\n";
    ofs << "#define " << guard << "_H\n\n";
    ofs << "// Generated by st-bin2rsx\n";
    ofs << "// Source: " << input_path << "\n";
    ofs << "const unsigned char " << array_name << "[" << data.size() << "] = {\n    ";

    for (size_t i = 0; i < data.size(); ++i) {
        ofs << "0x" << std::hex << std::uppercase << std::setfill('0') << std::setw(2) << (int)data[i];
        
        if (i != data.size() - 1) {
            ofs << ", ";
            if ((i + 1) % 12 == 0) ofs << "\n    ";
        }
    }

    ofs << "\n};\n\n";
    ofs << "#endif // " << guard << "_H\n";

    std::cout << "Successfully converted " << input_path << " to " << output_path << "\n";
    return 0;
}
